//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MemberExercisePlan
{
    public int Id { get; set; }
    public Nullable<int> MemberId { get; set; }
    public Nullable<int> ExercisePlanId { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<decimal> StartWeight { get; set; }
    public Nullable<decimal> StartWaist { get; set; }
    public Nullable<decimal> StartBodyFat { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<decimal> EndWeight { get; set; }
    public Nullable<decimal> EndWaist { get; set; }
    public Nullable<decimal> EndBodyFat { get; set; }
}

public partial class MemberExercisePlanWeek
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MemberExercisePlanWeek()
    {
        this.PrizeMemberLogs = new HashSet<PrizeMemberLog>();
    }

    public int Id { get; set; }
    public Nullable<int> MemberId { get; set; }
    public Nullable<int> ExercisePlanId { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<decimal> StartWeight { get; set; }
    public Nullable<decimal> StartWaist { get; set; }
    public Nullable<decimal> StartBodyFat { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<decimal> EndWeight { get; set; }
    public Nullable<decimal> EndWaist { get; set; }
    public Nullable<decimal> EndBodyFat { get; set; }
    public Nullable<int> ExercisePlanWeekId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeMemberLog> PrizeMemberLogs { get; set; }
}

public partial class PrizeExerciseDayTimeType
{
    public int Id { get; set; }
    public string DayTimeTypeName { get; set; }
    public string Image { get; set; }
}

public partial class PrizeExercisePlan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizeExercisePlan()
    {
        this.PrizeExercisePlanWeeks = new HashSet<PrizeExercisePlanWeek>();
    }

    public int Id { get; set; }
    public string PlanName { get; set; }
    public string Description { get; set; }
    public int ProgramId { get; set; }
    public int LocationId { get; set; }
    public int ExperienceId { get; set; }
    public int LevelId { get; set; }
    public Nullable<int> childPlanId { get; set; }

    public virtual PrizePlanProgram PrizePlanProgram { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeExercisePlanWeek> PrizeExercisePlanWeeks { get; set; }
}

public partial class PrizeExercisePlanWeek
{
    public int Id { get; set; }
    public Nullable<int> PrizeExercisePlanId { get; set; }
    public Nullable<int> PrizeFoodPlanId { get; set; }
    public Nullable<int> Week { get; set; }
    public string ExerciseDay1 { get; set; }
    public string ExerciseDay2 { get; set; }
    public string ExerciseDay3 { get; set; }
    public string ExerciseDay4 { get; set; }
    public string ExerciseDay5 { get; set; }
    public string ExerciseDay6 { get; set; }
    public string ExerciseDay7 { get; set; }
    public string Description { get; set; }

    public virtual PrizeExercisePlan PrizeExercisePlan { get; set; }
    public virtual PrizeFoodPlan PrizeFoodPlan { get; set; }
}

public partial class PrizeExerciseUnit
{
    public int Id { get; set; }
    public string Exercise { get; set; }
    public string Reps { get; set; }
    public string Rest { get; set; }
    public string Weight { get; set; }
    public string Comments { get; set; }
    public Nullable<int> UnitOrder { get; set; }
    public string Tempo { get; set; }
    public string Trainning_Set { get; set; }
}

public partial class PrizeExerciseUnitSet
{
    public int Id { get; set; }
    public int UnitSetNameId { get; set; }
    public int PrizeExerciseUnitId { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizeExerciseUnitSetForDay
{
    public int Id { get; set; }
    public int PrizeExercisePlanWeekId { get; set; }
    public int ExerciseDay { get; set; }
    public int PrizeExerciseUnitSetNameId { get; set; }
    public int DayTimeTypeId { get; set; }
}

public partial class PrizeExerciseUnitSetName
{
    public int Id { get; set; }
    public string UnitSetName { get; set; }
}

public partial class PrizeFoodPlan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizeFoodPlan()
    {
        this.PrizeExercisePlanWeeks = new HashSet<PrizeExercisePlanWeek>();
    }

    public int Id { get; set; }
    public string PlanName { get; set; }
    public string Description { get; set; }
    public string FoodDay1 { get; set; }
    public string FoodDay2 { get; set; }
    public string FoodDay3 { get; set; }
    public string FoodDay4 { get; set; }
    public string FoodDay5 { get; set; }
    public string FoodDay6 { get; set; }
    public string FoodDay7 { get; set; }
    public string Weeks { get; set; }
    public Nullable<int> ProgramId { get; set; }
    public Nullable<int> LocationId { get; set; }
    public Nullable<int> ExperienceId { get; set; }
    public Nullable<int> LevelId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeExercisePlanWeek> PrizeExercisePlanWeeks { get; set; }
}

public partial class PrizeMember
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizeMember()
    {
        this.PrizeMemberLogs = new HashSet<PrizeMemberLog>();
    }

    public int Id { get; set; }
    public Nullable<int> UmbracoId { get; set; }
    public string Firstname { get; set; }
    public string Surname { get; set; }
    public Nullable<System.DateTime> DoB { get; set; }
    public string Gender { get; set; }
    public string Country { get; set; }
    public string Email { get; set; }
    public string StreetAddress { get; set; }
    public string Suburb { get; set; }
    public string City { get; set; }
    public string Postcode { get; set; }
    public string State { get; set; }
    public Nullable<decimal> Height { get; set; }
    public Nullable<decimal> Weight { get; set; }
    public string Password { get; set; }
    public Nullable<decimal> Waist { get; set; }
    public Nullable<decimal> BodyFat { get; set; }
    public string GoalDescription { get; set; }
    public Nullable<decimal> GoalWeight { get; set; }
    public Nullable<decimal> GoalWaist { get; set; }
    public Nullable<decimal> GoalBodyFat { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeMemberLog> PrizeMemberLogs { get; set; }
}

public partial class PrizeMemberLog
{
    public int Id { get; set; }
    public Nullable<int> MemberId { get; set; }
    public Nullable<int> MemberExercisePlanId { get; set; }
    public Nullable<System.DateTime> LogDate { get; set; }
    public Nullable<decimal> Weight { get; set; }
    public Nullable<decimal> Waist { get; set; }
    public Nullable<decimal> BodyFat { get; set; }
    public string PhotoUrl { get; set; }

    public virtual MemberExercisePlanWeek MemberExercisePlanWeek { get; set; }
    public virtual PrizeMember PrizeMember { get; set; }
}

public partial class PrizePlanExperience
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizePlanLevel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizePlanLocation
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizePlanProgram
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizePlanProgram()
    {
        this.PrizeExercisePlans = new HashSet<PrizeExercisePlan>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeExercisePlan> PrizeExercisePlans { get; set; }
}
